import { StudentFormSchema, FormFieldDef, FormSectionDef } from "@/types/form-schema";

export const DEFAULT_FORM_SECTIONS: FormSectionDef[] = [
  {
    key: "administrative",
    title: "Administrative Information",
    description: "Official registration and school administrative tracking",
    step: 1,
    iconName: "Shield",
  },
  {
    key: "personal",
    title: "Personal Information",
    description: "Student identity, demographic profile, and personal details",
    step: 1,
    iconName: "User",
  },
  {
    key: "contact",
    title: "Contact Information",
    description: "Direct student communication and emergency contact credentials",
    step: 1,
    iconName: "Phone",
  },
  {
    key: "academic",
    title: "Academic Information",
    description: "Class admission, batch, section, and prior schooling history",
    step: 2,
    iconName: "GraduationCap",
  },
  {
    key: "address",
    title: "Address Information",
    description: "Permanent and temporary residential location details",
    step: 3,
    iconName: "MapPin",
  },
  {
    key: "guardian",
    title: "Guardian Information",
    description: "Parent, guardian contacts, and occupational background",
    step: 3,
    iconName: "Users",
  },
  {
    key: "medical",
    title: "Additional & Medical Details",
    description: "Health records, transport, hostel, and special accommodations",
    step: 4,
    iconName: "FileText",
  },
  {
    key: "custom_fields",
    title: "Custom Fields & Additional Data",
    description: "Institution-specific custom registration fields and records",
    step: 6,
    iconName: "SlidersHorizontal",
  },
];

export const DEFAULT_ACTIVE_FIELDS: FormFieldDef[] = [
  // Administrative Section (Step 1)
  {
    id: "f_app_no",
    key: "applicationFormNo",
    label: "Application Form No.",
    type: "text",
    required: false,
    section: "administrative",
    order: 1,
  },
  {
    id: "f_sgi_no",
    key: "sgiNo",
    label: "SGI No.",
    type: "text",
    required: false,
    section: "administrative",
    order: 2,
  },
  {
    id: "f_scholarship",
    key: "scholarship",
    label: "Scholarship",
    type: "select",
    required: false,
    section: "administrative",
    options: [
      { label: "Select Scholarship", value: "" },
      { label: "Academic Merit 100%", value: "Merit 100%" },
      { label: "Academic Merit 50%", value: "Merit 50%" },
      { label: "Need-Based Financial Aid", value: "Need Based" },
      { label: "Sibling Concession 25%", value: "Sibling 25%" },
      { label: "Staff Ward Concession", value: "Staff Ward" },
    ],
    order: 3,
  },
  {
    id: "f_quota",
    key: "quotaType",
    label: "Quota Type",
    type: "select",
    required: false,
    section: "administrative",
    options: [
      { label: "General Quota", value: "General Quota" },
      { label: "Government Quota", value: "Government Quota" },
      { label: "Management Quota", value: "Management Quota" },
      { label: "Differently Abled Quota", value: "Differently Abled Quota" },
    ],
    order: 4,
  },
  {
    id: "f_univ_reg",
    key: "universityRegNo",
    label: "University / Board Reg No.",
    type: "text",
    required: false,
    section: "administrative",
    placeholder: "e.g. NEB-2083-9941",
    order: 5,
  },
  {
    id: "f_reg_bs",
    key: "registrationDateBS",
    label: "Registration Date (BS)",
    type: "text",
    required: false,
    section: "administrative",
    placeholder: "YYYY-MM-DD (BS)",
    order: 6,
  },
  {
    id: "f_reg_ad",
    key: "registrationDateAD",
    label: "Registration Date (AD)",
    type: "date",
    required: false,
    section: "administrative",
    order: 7,
  },

  // Personal Information (Step 1)
  {
    id: "f_fname",
    key: "firstName",
    label: "First Name",
    type: "text",
    required: true,
    section: "personal",
    systemLocked: true,
    placeholder: "e.g. Aarav",
    order: 1,
  },
  {
    id: "f_mname",
    key: "middleName",
    label: "Middle Name",
    type: "text",
    required: false,
    section: "personal",
    placeholder: "e.g. Kumar",
    order: 2,
  },
  {
    id: "f_lname",
    key: "lastName",
    label: "Last Name",
    type: "text",
    required: true,
    section: "personal",
    systemLocked: true,
    placeholder: "e.g. Sharma",
    order: 3,
  },
  {
    id: "f_name_nepali",
    key: "fullNameNepali",
    label: "Full Name Nepali",
    type: "text",
    required: false,
    section: "personal",
    placeholder: "Type in English or Nepali, e.g. Rupesh Sharma",
    order: 4,
  },
  {
    id: "f_gender",
    key: "gender",
    label: "Gender",
    type: "select",
    required: false,
    section: "personal",
    options: [
      { label: "Male", value: "Male" },
      { label: "Female", value: "Female" },
      { label: "Other", value: "Other" },
    ],
    order: 5,
  },
  {
    id: "f_dob_bs",
    key: "dobBS",
    label: "Date of Birth (BS)",
    type: "text",
    required: false,
    section: "personal",
    placeholder: "YYYY-MM-DD (BS)",
    order: 6,
  },
  {
    id: "f_dob_ad",
    key: "dobAD",
    label: "Date of Birth (AD)",
    type: "date",
    required: false,
    section: "personal",
    order: 7,
  },
  {
    id: "f_ethnic",
    key: "ethnicGroup",
    label: "Ethnic Group",
    type: "select",
    required: false,
    section: "personal",
    options: [
      { label: "Brahmin / Chhetri", value: "Brahmin / Chhetri" },
      { label: "Janajati", value: "Janajati" },
      { label: "Dalit", value: "Dalit" },
      { label: "Madhesi", value: "Madhesi" },
      { label: "Muslim", value: "Muslim" },
      { label: "Other", value: "Other" },
    ],
    order: 8,
  },
  {
    id: "f_caste",
    key: "caste",
    label: "Caste",
    type: "select",
    required: false,
    section: "personal",
    options: [
      { label: "Brahmin", value: "Brahmin" },
      { label: "Chhetri", value: "Chhetri" },
      { label: "Newar", value: "Newar" },
      { label: "Gurung", value: "Gurung" },
      { label: "Magar", value: "Magar" },
      { label: "Rai / Limbu", value: "Rai / Limbu" },
      { label: "Tamang", value: "Tamang" },
      { label: "Yadav", value: "Yadav" },
      { label: "Tharu", value: "Tharu" },
      { label: "Other", value: "Other" },
    ],
    order: 9,
  },
  {
    id: "f_marital",
    key: "maritalStatus",
    label: "Marital Status",
    type: "select",
    required: false,
    section: "personal",
    options: [
      { label: "Single", value: "Single" },
      { label: "Married", value: "Married" },
    ],
    order: 10,
  },
  {
    id: "f_lang",
    key: "language",
    label: "Language",
    type: "select",
    required: false,
    section: "personal",
    options: [
      { label: "Nepali", value: "Nepali" },
      { label: "English", value: "English" },
      { label: "Maithili", value: "Maithili" },
      { label: "Bhojpuri", value: "Bhojpuri" },
      { label: "Newari", value: "Newari" },
      { label: "Hindi", value: "Hindi" },
    ],
    order: 11,
  },
  {
    id: "f_nationality",
    key: "nationality",
    label: "Nationality",
    type: "select",
    required: false,
    section: "personal",
    options: [
      { label: "Nepali", value: "Nepali" },
      { label: "Indian", value: "Indian" },
      { label: "Other", value: "Other" },
    ],
    order: 12,
  },
  {
    id: "f_religion",
    key: "religion",
    label: "Religion",
    type: "select",
    required: false,
    section: "personal",
    options: [
      { label: "Hinduism", value: "Hinduism" },
      { label: "Buddhism", value: "Buddhism" },
      { label: "Islam", value: "Islam" },
      { label: "Christianity", value: "Christianity" },
      { label: "Kirat", value: "Kirat" },
      { label: "Other", value: "Other" },
    ],
    order: 13,
  },

  // Contact Information (Step 1)
  {
    id: "f_mobile",
    key: "mobile",
    label: "Mobile Number",
    type: "phone",
    required: false,
    section: "contact",
    placeholder: "+977-98XXXXXXXX",
    order: 1,
  },
  {
    id: "f_email",
    key: "email",
    label: "Email Address",
    type: "email",
    required: false,
    section: "contact",
    placeholder: "student@example.com",
    order: 2,
  },
  {
    id: "f_blood",
    key: "bloodGroup",
    label: "Blood Group",
    type: "select",
    required: false,
    section: "contact",
    options: [
      { label: "A+", value: "A+" },
      { label: "A-", value: "A-" },
      { label: "B+", value: "B+" },
      { label: "B-", value: "B-" },
      { label: "AB+", value: "AB+" },
      { label: "AB-", value: "AB-" },
      { label: "O+", value: "O+" },
      { label: "O-", value: "O-" },
    ],
    order: 3,
  },
  {
    id: "f_citizenship",
    key: "citizenshipNo",
    label: "Citizenship No.",
    type: "text",
    required: false,
    section: "contact",
    placeholder: "e.g. 27-01-79-10928",
    order: 4,
  },
  {
    id: "f_passport",
    key: "passportNo",
    label: "Passport No.",
    type: "text",
    required: false,
    section: "contact",
    placeholder: "e.g. NP-992140",
    order: 5,
  },
  {
    id: "f_national_id",
    key: "nationalIdNo",
    label: "National ID No.",
    type: "text",
    required: false,
    section: "contact",
    placeholder: "e.g. 1029384756",
    order: 6,
  },

  // Academic Details (Step 2)
  {
    id: "f_class",
    key: "class",
    label: "Class / Grade",
    type: "select",
    required: true,
    section: "academic",
    systemLocked: true,
    options: [
      { label: "Grade 1", value: "Grade 1" },
      { label: "Grade 2", value: "Grade 2" },
      { label: "Grade 3", value: "Grade 3" },
      { label: "Grade 4", value: "Grade 4" },
      { label: "Grade 5", value: "Grade 5" },
      { label: "Grade 6", value: "Grade 6" },
      { label: "Grade 7", value: "Grade 7" },
      { label: "Grade 8", value: "Grade 8" },
      { label: "Grade 9", value: "Grade 9" },
      { label: "Grade 10", value: "Grade 10" },
      { label: "Grade 11 - Science", value: "Grade 11 - Science" },
      { label: "Grade 11 - Management", value: "Grade 11 - Management" },
      { label: "Grade 12 - Science", value: "Grade 12 - Science" },
      { label: "Grade 12 - Management", value: "Grade 12 - Management" },
    ],
    order: 1,
  },
  {
    id: "f_section",
    key: "section",
    label: "Section",
    type: "select",
    required: true,
    section: "academic",
    systemLocked: true,
    options: [
      { label: "Section A", value: "Section A" },
      { label: "Section B", value: "Section B" },
      { label: "Section C", value: "Section C" },
      { label: "Section D", value: "Section D" },
    ],
    order: 2,
  },
  {
    id: "f_roll",
    key: "rollNumber",
    label: "Roll Number",
    type: "text",
    required: true,
    section: "academic",
    systemLocked: true,
    order: 3,
  },
  {
    id: "f_batch",
    key: "batch",
    label: "Batch / Academic Year",
    type: "select",
    required: true,
    section: "academic",
    systemLocked: true,
    options: [
      { label: "2083/84", value: "2083/84" },
      { label: "2082/83", value: "2082/83" },
      { label: "2081/82", value: "2081/82" },
    ],
    order: 4,
  },
  {
    id: "f_prev_school",
    key: "previousSchoolName",
    label: "Previous School Name",
    type: "text",
    required: false,
    section: "academic",
    order: 5,
  },
  {
    id: "f_prev_gpa",
    key: "previousGradeGpa",
    label: "Previous Grade / GPA",
    type: "text",
    required: false,
    section: "academic",
    order: 6,
  },
  {
    id: "f_tc_no",
    key: "transferCertificateNo",
    label: "Transfer Certificate (TC) No.",
    type: "text",
    required: false,
    section: "academic",
    order: 7,
  },

  // Address Information (Step 3)
  {
    id: "f_country",
    key: "country",
    label: "Country",
    type: "text",
    required: false,
    section: "address",
    order: 1,
  },
  {
    id: "f_province",
    key: "province",
    label: "Province",
    type: "select",
    required: false,
    section: "address",
    options: [
      { label: "Koshi Province", value: "Koshi Province" },
      { label: "Madhesh Province", value: "Madhesh Province" },
      { label: "Bagmati Province", value: "Bagmati Province" },
      { label: "Gandaki Province", value: "Gandaki Province" },
      { label: "Lumbini Province", value: "Lumbini Province" },
      { label: "Karnali Province", value: "Karnali Province" },
      { label: "Sudurpashchim Province", value: "Sudurpashchim Province" },
    ],
    order: 2,
  },
  {
    id: "f_district",
    key: "district",
    label: "District",
    type: "text",
    required: true,
    section: "address",
    order: 3,
  },
  {
    id: "f_municipality",
    key: "municipality",
    label: "Municipality / Rural Municipality",
    type: "text",
    required: true,
    section: "address",
    order: 4,
  },
  {
    id: "f_ward",
    key: "wardNo",
    label: "Ward No.",
    type: "text",
    required: false,
    section: "address",
    order: 5,
  },
  {
    id: "f_tole",
    key: "tole",
    label: "Tole / Landmark",
    type: "text",
    required: false,
    section: "address",
    order: 6,
  },
  {
    id: "f_address",
    key: "address",
    label: "Street Address",
    type: "text",
    required: true,
    section: "address",
    order: 7,
  },

  // Guardian Information (Step 3)
  {
    id: "f_guardian_name",
    key: "guardianName",
    label: "Guardian Name",
    type: "text",
    required: true,
    section: "guardian",
    order: 1,
  },
  {
    id: "f_relation",
    key: "relation",
    label: "Relationship to Student",
    type: "select",
    required: true,
    section: "guardian",
    options: [
      { label: "Father", value: "Father" },
      { label: "Mother", value: "Mother" },
      { label: "Guardian", value: "Guardian" },
      { label: "Uncle / Aunt", value: "Uncle / Aunt" },
      { label: "Grandparent", value: "Grandparent" },
    ],
    order: 2,
  },
  {
    id: "f_guardian_mob",
    key: "guardianMobile",
    label: "Guardian Mobile",
    type: "phone",
    required: true,
    section: "guardian",
    order: 3,
  },
  {
    id: "f_guardian_email",
    key: "guardianEmail",
    label: "Guardian Email",
    type: "email",
    required: false,
    section: "guardian",
    order: 4,
  },
  {
    id: "f_guardian_occ",
    key: "guardianOccupation",
    label: "Guardian Occupation",
    type: "text",
    required: false,
    section: "guardian",
    order: 5,
  },
  {
    id: "f_parents_edu",
    key: "parentsEducation",
    label: "Parents Education Level",
    type: "text",
    required: false,
    section: "guardian",
    order: 6,
  },
  {
    id: "f_annual_income",
    key: "annualIncome",
    label: "Annual Family Income",
    type: "text",
    required: false,
    section: "guardian",
    order: 7,
  },

  // Medical & Additional Details (Step 4)
  {
    id: "f_bp",
    key: "bloodPressure",
    label: "Blood Pressure",
    type: "text",
    required: false,
    section: "medical",
    order: 1,
  },
  {
    id: "f_height",
    key: "heightInch",
    label: "Height (Inches)",
    type: "number",
    required: false,
    section: "medical",
    order: 2,
  },
  {
    id: "f_weight",
    key: "weightKg",
    label: "Weight (Kg)",
    type: "number",
    required: false,
    section: "medical",
    order: 3,
  },
  {
    id: "f_med_conditions",
    key: "medicalConditions",
    label: "Medical Conditions / Allergies",
    type: "text",
    required: false,
    section: "medical",
    order: 4,
  },
  {
    id: "f_health_notes",
    key: "healthNotes",
    label: "Health Status Notes",
    type: "textarea",
    required: false,
    section: "medical",
    order: 5,
  },
  {
    id: "f_hospital",
    key: "hospitalName",
    label: "Emergency Hospital",
    type: "text",
    required: false,
    section: "medical",
    order: 6,
  },
  {
    id: "f_doctor",
    key: "doctorName",
    label: "Family Doctor Name",
    type: "text",
    required: false,
    section: "medical",
    order: 7,
  },
  {
    id: "f_bus_opt",
    key: "isBus",
    label: "School Bus Transport Required",
    type: "checkbox",
    required: false,
    section: "medical",
    order: 8,
  },
  {
    id: "f_hostel_opt",
    key: "isHostel",
    label: "Hostel Accommodation Required",
    type: "checkbox",
    required: false,
    section: "medical",
    order: 9,
  },
];

export const DEFAULT_UNUSED_FIELDS: FormFieldDef[] = [
  {
    id: "f_unused_edj",
    key: "edjStatus",
    label: "EDJ (Economically Disadvantaged Janajati)",
    type: "select",
    required: false,
    section: "personal",
    options: [
      { label: "Yes", value: "Yes" },
      { label: "No", value: "No" },
    ],
    order: 99,
  },
  {
    id: "f_unused_temp_country",
    key: "tempCountry",
    label: "Temp Country",
    type: "text",
    required: false,
    section: "address",
    order: 100,
  },
  {
    id: "f_unused_temp_tole",
    key: "tempTole",
    label: "Temp Tole",
    type: "text",
    required: false,
    section: "address",
    order: 101,
  },
  {
    id: "f_unused_guardian_alt_phone",
    key: "guardianAltPhone",
    label: "Guardian Alternative Phone",
    type: "phone",
    required: false,
    section: "guardian",
    order: 102,
  },
  {
    id: "f_unused_bus_route",
    key: "preferredBusRoute",
    label: "Preferred Bus Route Number",
    type: "text",
    required: false,
    section: "medical",
    order: 103,
  },
];

export const INITIAL_STUDENT_FORM_SCHEMA: StudentFormSchema = {
  version: 1,
  sections: DEFAULT_FORM_SECTIONS,
  activeFields: DEFAULT_ACTIVE_FIELDS,
  unusedFields: DEFAULT_UNUSED_FIELDS,
};

export const SCHEMA_STORAGE_KEY = "SCHOOL_ERP_STUDENT_FORM_SCHEMA_V1";
