/**
 * Centralized Route Map for School ERP
 */

export const ROUTES = {
  HOME: "/",
  LOGIN: "/login",
  FORGOT_PASSWORD: "/forgot-password",

  // Core ERP Modules
  DASHBOARD: "/dashboard",
  SCHOOLS: {
    ROOT: "/schools",
    CREATE: "/schools/new",
    DETAIL: (id: string) => `/schools/${id}`,
    SETTINGS: (id: string) => `/schools/${id}/settings`,
  },
  STUDENTS: {
    ROOT: "/students",
    ADMISSION: "/students/admission",
    DISABLE: "/students/disable",
    DISABLED: "/students/disabled",
    DELETED: "/students/deleted",
    DETAIL: (id: string) => `/students/${id}`,
    ATTENDANCE: "/students/attendance",
    PROMOTION: "/students/promotion",
  },
  ACADEMICS: {
    ROOT: "/academics",
    CLASSES: "/academics/classes",
    SECTIONS: "/academics/sections",
    SUBJECTS: "/academics/subjects",
    TIMETABLE: "/academics/timetable",
    SYLLABUS: "/academics/syllabus",
  },
  TEACHERS: {
    ROOT: "/teachers",
    CREATE: "/teachers/new",
    DETAIL: (id: string) => `/teachers/${id}`,
    ALLOCATION: "/teachers/allocation",
  },
  FEES: {
    ROOT: "/fees",
    COLLECTION: "/fees/collection",
    STRUCTURE: "/fees/structure",
    INVOICES: "/fees/invoices",
    REPORTS: "/fees/reports",
    LEDGER: "/fees/ledger",
    HISTORY: "/fees/history",
    DUE_LIST: "/fees/due-list",
    ONLINE_PAYMENT: "/fees/online-payment",
    REFUNDS: "/fees/refunds",
    DISCOUNTS: "/fees/discounts",
    PENDING: "/fees/pending",
    SUMMARY: "/fees/summary",
    COUNTER_CLOSING: "/fees/counter-closing",
    ACCOUNTS: {
      CHART_OF_ACCOUNTS: "/fees/accounts/chart-of-accounts",
      GENERAL_LEDGER: "/fees/accounts/general-ledger",
      PARTY_LEDGERS: "/fees/accounts/party-ledgers",
      JOURNAL_ENTRIES: "/fees/accounts/journal-entries",
      CASH_BANK_BOOKS: "/fees/accounts/cash-bank-books",
      EXPENSES: "/fees/accounts/expenses",
      SETTINGS: "/fees/accounts/settings",
    },
    SETUP: {
      ROOT: "/fees/setup",
      PROGRAM_FEE: "/fees/setup/program-fee",
      PROGRAM_TOTAL: "/fees/setup/program-total",
      PROGRAM_ANNUAL: "/fees/setup/program-annual",
      PROGRAM_SEMESTER: "/fees/setup/program-semester",
      CLASS_FEE: "/fees/setup/class-fee",
      CLASS_ANNUAL: "/fees/setup/class-annual",
      CLASS_MONTHLY: "/fees/setup/class-monthly",
      STUDENT_CUSTOM: "/fees/setup/student-custom",
      STUDENT_SCHEDULE: "/fees/setup/student-schedule",
      ASSIGN: "/fees/setup/assign",
      ASSIGN_PROGRAM: "/fees/setup/assign-program",
      ASSIGN_CLASS: "/fees/setup/assign-class",
      ASSIGN_STUDENT: "/fees/setup/assign-student",
      ASSIGN_MISC: "/fees/setup/assign-misc",
      SCHOLARSHIPS: "/fees/setup/scholarships",
      INSTALLMENTS: "/fees/setup/installments",
      FINES: "/fees/setup/fines",
      SETTINGS: "/fees/setup/settings",
      INVOICE_SETUP: "/fees/setup/invoice-setup",
      INVOICE_TEMPLATE: "/fees/setup/invoice-template",
    },
  },
  EXAMS: {
    ROOT: "/examinations",
    SCHEDULE: "/examinations/schedule",
    MARKS_ENTRY: "/examinations/marks",
    REPORT_CARDS: "/examinations/report-cards",
  },
  STAFF: {
    ROOT: "/staff",
    PAYROLL: "/staff/payroll",
    ATTENDANCE: "/staff/attendance",
    LEAVE: "/staff/leave",
  },
  REPORTS: {
    ROOT: "/reports",
    ATTENDANCE: "/reports/attendance",
    FINANCIAL: "/reports/financial",
    ACADEMIC: "/reports/academic",
  },
  SETTINGS: {
    ROOT: "/settings",
    GENERAL: "/settings/general",
    ROLES: "/settings/roles-permissions",
    BACKUP: "/settings/backup",
    AUDIT_LOGS: "/settings/audit-logs",
  },
} as const;
